"""empty message

Revision ID: 11241c8ff50b
Revises: 82a2aa1e8d0f
Create Date: 2021-04-28 17:46:45.119283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11241c8ff50b'
down_revision = '82a2aa1e8d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(length=120), nullable=True))
    op.add_column('shows', sa.Column('venue_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###
