"""empty message

Revision ID: 570a095eb86c
Revises: 
Create Date: 2021-04-27 17:54:49.578178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570a095eb86c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
