"""empty message

Revision ID: 69951455e4c5
Revises: 11241c8ff50b
Create Date: 2021-04-28 18:31:58.729991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69951455e4c5'
down_revision = '11241c8ff50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'past_shows_count')
    # ### end Alembic commands ###
