"""empty message

Revision ID: 82a2aa1e8d0f
Revises: 570a095eb86c
Create Date: 2021-04-28 15:40:05.743214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a2aa1e8d0f'
down_revision = '570a095eb86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'page_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('page_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
